[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = ""
name = "BayesAnalyses"
version = "0.1"
[tool.poetry.dependencies]
python = "^3.8"
[tool.poetry.dev-dependencies]
pytest = "^3.4"
